### ISSUE TITLE
Integrate JavaScript games into the game page

### ISSUE THREAD

**Issue by shontzu** [yuuchin/GreatKidsShow#2]
@ngeojiajun any idea how we should handle the game integration? should we 
- embed the game straight into the game page
- make a popup window 
- redirect to another page
- ???

**Comment by ngeojiajun** [comment]
hmm maybe <iframe>? or directly append the game into the dom list?

**Comment by ngeojiajun** [comment]
partial implemention here
https://github.com/yuuchin/GreatKidsShow/pull/5/commits/fc6b56e96782573d5b28637f750257c3e3ab689a
